catalog/urls.py
from django.conf.urls.defaults import *

urlpatterns=patterns('iStore.catalog.views',
                     (r'^$','index',{'template_name':'catalog/index.html'},'catalog_home'),
                     (r'^category/(?P<category_slug>[-\w]+)/$','show_category',
                    {'template_name':'catalog/category.html'},'catalog_category'),
                     (r'^product/(?P<product_slug>[-\w]+)/$','show_product',
                   {'template_name':'catalog/product.html'},'catalog_product'),

)

urls.py
from django.conf.urls.defaults import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
import settings
admin.autodiscover()

urlpatterns = patterns('preview.views',
    #(r'^catalog/$','views.home'),
    (r'^catalog/$','home'),
    (r'^catalog/about/','about'),
    (r'^catalog/privacy/','privacy'),
    (r'^catalog/projects/','projects'),
    (r'^catalog/contacts/','contacts'),
    (r'^accounts/', include('accounts.urls')),
    (r'^accounts/',include('django.contrib.auth.urls')),
    #(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT}),
    
    # Example:
    # (r'^iStore/', include('iStore.foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
)
urlpatterns+=patterns('',
     (r'^search/',include('search.urls')),
     (r'^comment/product/add','comments.views.addComments'),
     (r'^admin/', include(admin.site.urls)),
     (r'^cart/',include('cart.urls')),
     (r'^',include('catalog.urls')),
     (r'rating/$','rate.views.addRating'),
     (r'^checkout/$','checkout.views.check_out'),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() #this serves static files and media files.
    #in case media is not served correctly
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            }),
    )

handler404 = 'iStore.views.file_not_found_404'

catalog/models.py
from django.db import models
class ActiveCategoryManager(models.Manager):
      def get_query_set(self):
        return super(ActiveCategoryManager, self).get_query_set().filter(is_active=True)
class Category(models.Model):
     name=models.CharField(max_length=50)
     slug=models.SlugField(max_length=50,unique=True, help_text='Unique value for product page URL, created from name.')
     description=models.TextField()
     is_active=models.BooleanField(default=True)
     meta_keywords=models.CharField("Meta Keywords", max_length=255, help_text='Comma-delimited set of SEO keywords for meta tag')
     created_at=models.DateTimeField(auto_now_add=True)
     updated_at=models.DateTimeField(auto_now=True)
     objects = models.Manager()
     active = ActiveCategoryManager()
     class Meta:
          db_table='categories'
          ordering=['-created_at']
          verbose_name_plural='Categories'
   
     def __unicode__(self):
          return self.name

     @models.permalink
     def get_absolute_url(self):
         return ('catalog_category',(),{'category_slug':self.slug})
class ActiveProductManager(models.Manager):
     def get_query_set(self):
	     return super(ActiveProductManager,self).get_query_set().filter(is_active=True)
class Product(models.Model):
     name=models.CharField(max_length=255,unique=True)
     slug=models.SlugField(max_length=255,unique=True,help_text='Unique value for product page URL, create from name.')
     brand=models.CharField(max_length=50)
     sku=models.CharField(max_length=50)
     price=models.DecimalField(max_digits=9,decimal_places=2)
     old_price=models.DecimalField(max_digits=9,decimal_places=2, blank=True, default=0.00)
     #image=models.CharField(max_length=50)
     image= models.ImageField(upload_to='images/products/main')
     thumbnail=models.ImageField(upload_to='images/products/thumbnails')
     image_caption=models.CharField(max_length=200)
     is_active=models.BooleanField(default=True)
     is_bestseller= models.BooleanField(default=False)
     is_featured=models.BooleanField(default=False)
     quantity=models.IntegerField()
     description= models.TextField()
     meta_keywords=models.CharField(max_length=255,help_text='Comma-delimited set of SEO keywords for meta tag')
     meta_description=models.CharField(max_length=255,help_text='Content for description meta tag')
     created_at=models.DateTimeField(auto_now_add=True)
     updated_at=models.DateTimeField(auto_now=True)
     categories=models.ManyToManyField(Category)
     objects = models.Manager()
     active = ActiveProductManager()
	 
     class Meta:
         db_table='products'
         ordering=['-created_at']
     def __unicode__(self):
         return self.name
     @models.permalink
     def get_absolute_url(self):
         return ('catalog_product',(),{'product_slug':self.slug})
     def sale_price(self):
         if self.old_price>self.price:
            return self.price
         else:
            return None

comments/models.py
from django.db import models
from catalog.models import Product


class Comments(models.Model):
         comment= models.TextField()
         name= models.CharField(max_length=50)
         score= models.DecimalField(blank=True,default=0,max_digits=4, decimal_places=1)
         add_time=models.DateTimeField(auto_now=True)
         p=models.CharField(max_length=50)
         class Meta:
           db_table='comments'
		 
         def __unicode__(self):
            return self.name		 

catalog/forms.py
from django import forms
from iStore.catalog.models import Product

class ProductAdminForm(forms.ModelForm):
     class Meta:
          model=Product
          
          def clean_price(self):
              if self.cleaned_data['price']<=0:
                  raise forms.ValidationError('Price must be greater than zero.')
              return self.cleaned_data['price']


class ProductAddToCartForm(forms.Form):
       quantity = forms.IntegerField(widget=forms.TextInput(attrs={'size':'2','value':'1', 'class':'quantity', 'maxlength':'5'}),error_messages={'invalid':'Please enter a valid quantity.'},min_value=1)
       product_slug = forms.CharField(widget=forms.HiddenInput())
# override the default __init__ so we can set the request
       def __init__(self, request=None, *args, **kwargs):
          self.request = request
          super(ProductAddToCartForm, self).__init__(*args, **kwargs)
# custom validation to check for cookies
       def clean(self):
          if self.request:
            if not self.request.session.test_cookie_worked():
               raise forms.ValidationError("Cookies must be enabled.")
          return self.cleaned_data

catalog/views.py
from __future__ import division 
from django.shortcuts import get_object_or_404, render_to_response
from iStore.catalog.models import Category, Product
from django.template import RequestContext
from django.core import urlresolvers
from iStore.cart import cart
from iStore.rate.models import *
from iStore.comments.models import *
from django.http import HttpResponseRedirect
from iStore.catalog.forms import ProductAddToCartForm
#from iStore.catalog.forms import ProductAddToCartForm
from django.http import HttpResponse
import datetime

def index(request, template_name="catalog/index.html"):
      products=Product.objects.all().order_by('?')[:6]
      return render_to_response(template_name, locals(),context_instance=RequestContext(request))
		   
def show_category(request, category_slug, template_name="catalog/category.html"):
     c = get_object_or_404(Category, slug=category_slug)
     products = c.product_set.all()
     page_title = c.name
     meta_keywords = c.meta_keywords
     #meta_description = c.meta_description
     return render_to_response(template_name, locals(),context_instance=RequestContext(request))

	 
def show_product(request, product_slug, template_name="catalog/product.html"):
    p = get_object_or_404(Product, slug=product_slug)
    categories = p.categories.all()
    page_title = p.name
    p_id=p.id
 
    rr=Rate.objects.get_or_create(votes=3,score=9,p_id=p_id)
    r=Rate.objects.get(p_id=p_id)   
    average=int(round(r.score / r.votes,0))
    co=Comments.objects.filter(p=p_id).order_by("-add_time")
    
    		  
    now=datetime.datetime.now()
    meta_keywords = p.meta_keywords
    meta_description = p.meta_description
    description=p.description
    description_short=description[0:250]
    comment_count=co.count()
    # need to evaluate the HTTP method
    if request.method == 'POST':
       postdata = request.POST.copy()
       form = ProductAddToCartForm(request, postdata)
#check if posted data is valid
       if form.is_valid():
#add to cart and redirect to cart page
         cart.add_to_cart(request)
# if test cookie worked, get rid of it
         if request.session.test_cookie_worked():
            request.session.delete_test_cookie()
         url = urlresolvers.reverse('show_cart')
         return HttpResponseRedirect(url)
    else:
     form = ProductAddToCartForm(request=request, label_suffix=':')
# assign the hidden input the product slug
    form.fields['product_slug'].widget.attrs['value'] = product_slug
# set the test cookie on our first GET request
    request.session.set_test_cookie()
    return render_to_response("catalog/product.html", locals(),context_instance=RequestContext(request))

comments/views.py
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from iStore.comments.models import *
#from iStore.catalog.views import *
import json
from django.http import HttpResponse, Http404 
from django.contrib.auth import logout
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required


#@login_required	 
def addComments(request):
    if request.method != 'POST':
	     raise Http404('Only POSTs are allowed')
		 
    #if request.session.get('has_commented',True):	 
    productId=request.POST.get('productid')
    score1=request.POST.get('score')
    comments1=request.POST.get('comments')
    name1=request.POST.get('name')
    add_time1=request.POST.get('time')
    b=Comments(comment=comments1,name=name1,score=score1,add_time=add_time1,p=productId)
    b.save()
    res={ "status": "successful","comment":comments1,"score":score1,"name":name1,"add_time":add_time1}
    data=json.dumps(res, indent=4)
    response = HttpResponse(data)
         #request.session['has_commented']= False
    return response	 

templates/catalog/category.html
{% extends "catalog.html" %}

{% block content %}

    <br>
    {% for p in products %}
      {% include 'tags/product_thumbnail.html' %}
       
     
    {% endfor %}
{% endblock %}

templates/catalog/comment.html
<div class="review">
	Rating: {{ b1.score }}
	by {{ b1.name }}
	<br />
	{{ b1.comment }}
	<br /><br />
	<hr />
</div>  

templates/catalog/index.html
{% extends "catalog.html" %}

{% block content %}
{% for p in products %}
      {% include 'tags/product_thumbnail.html' %}
       
     
    {% endfor %}
{% endblock %}

templates/catalog/product.html
{% extends "catalog.html" %}
{% block content %}
<div id="contentpic">
	<h1>{{ p.name }}</h1>
    <div class="product_image" >
     <img src="{{ MEDIA_URL }}{{ p.image }}" alt="{{ p.name }}" />
    </div>
</div>
<div id="contentfig">
    Brand: <em>{{ p.brand }}</em>
    <br />
   <b>{{ p.sku }}</b> available
   <br />
  In categor{{ categories.count|pluralize:"y,ies" }}:
    {% for c in categories %}
<a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
{% if not forloop.last %}, {% endif %}
    {% endfor %}
    <br />
{% if p.sale_price %}
    Was: <del>€ {{ p.old_price }}</del>
    <br />
    Now: € {{ p.price }}
{% else %}
    Price: € {{ p.price }}
{% endif %}
{{average}}
<form method="post" action="." class="cart">
   {{ form.as_p }}
  <br />
  <button type="submit" class="add" name="submit"></button>
  <button type="submit" class="check" name="check"></button>
  {% csrf_token %}
</form>
</div>

<script type="text/javascript">


function loadXMLDoc(rate)
{
	var xmlhttp;
	if (window.XMLHttpRequest)
	  {// code for IE7+, Firefox, Chrome, Opera, Safari
		xmlhttp=new XMLHttpRequest();
	  }
	else
	  {// code for IE6, IE5
		xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
	  }
	xmlhttp.onreadystatechange=function()
	  {
		if (xmlhttp.readyState==4 && xmlhttp.status==200)
		{
			var temp=xmlhttp.responseText.split(',');
			document.getElementById("t_votes").innerHTML=temp[0];
			//document.getElementById("myDiv").innerHTML=temp[1];
			document.getElementById("t_ava").innerHTML=temp[1];
			$('.rate_widget #'+temp[1]).prevAll().andSelf().addClass('ratings_over'); 
		}
	  }
	xmlhttp.open("GET","rating?productid="+{{ p.id }}+"&rate="+rate,true);
	xmlhttp.send();
	
	$('.movie_choice #'+rate).prevAll().andSelf().addClass('ratings_over');
	$('.movie_choice .ratings_stars').unbind("mouseover").unbind("mouseout");

	$("#myDiv").val(rate);
}

function addComment(){
	var sco=$("#myDiv").val();
	comment = { comments: $("#id_comment").val(),
				productid: $("#product_id").val(),
				score: sco,//change here later
				name:$("#name").val(),
				time:$("#time").val()
			};
	$.post("/comment/product/add/", comment,
			function(response){
				if (response.status == "successful"){
				
					$("#add_comment").attr('disabled','disabled');
					$("#comments").prepend(response.comment);
					$("#id_comment").val("");
					$("#name").val("");
					//$("#comments").append(response);
				}
		}, "json");
}
$(document).ready(function() {
	$("#add_comment").click(addComment);
	var average = $("#average").val();
	$('.rate_widget #'+average).prevAll().andSelf().addClass('ratings_over'); 

	$(".movie_choice .ratings_stars").hover(mouseIn,mouseOut);
	// Handles the mouseover 
	function mouseIn() {

	$(this).prevAll().andSelf().addClass('ratings_over'); 
	$(this).nextAll().removeClass('ratings_vote'); 
	//var pid = $("#pid").val();
	//$("#show").html("rate="+this.id+" ,p_id="+pid);
	}
	// Handles the mouseout 
	function mouseOut() {
	$(this).prevAll().andSelf().removeClass('ratings_over');
	$('.rate_widget #'+average).prevAll().andSelf().addClass('ratings_over');  
	set_votes($(this).parent());
	}

	$(function() {
	// setup ul.tabs to work as tabs for each div directly under div.panes
		$("ul.tabs").tabs("div.panes > div");
	})
});
</script>
<script type="text/javascript"> 
    hs.graphicsDir = '/static/highslide/graphics/';
    hs.outlineType = 'rounded-white';
	
	function reply(name) {
		$("#id_comment").val("To "+name+": ");	
	}
</script>
<script src="http://cdn.jquerytools.org/1.2.5/full/jquery.tools.min.js"></script>

<ul class="tabs">
	<li><a href="#">Description</a></li>
	<li><a href="#">Comments ({{ comment_count }})</a></li>
</ul>

<div class="panes">
	<div id="contentdes">
	{{description_short}}
	<a href="#" onclick="return hs.htmlExpand(this, { contentId: 'highslide-html' } )"
		class="highslide">
	 Read More...
	</a>

	
	</div>

	<div id="comments">
		<table id="comment">
			{% for comment in co %}
				<tr>
					<td id="profile">
						<img src="/static/images/user.gif" alt={{comment.name}} title={{comment.name}} class="avatar"/><br />
						{{comment.name}}
						<input type="hidden" id="scorevalue" value={{comment.score}} />				
					</td>
					<td>
					<span> 
						<span id="star1" class="ratings_stars{% if comment.score >= 1 %} ratings_over{% endif %}"></span>
						<span id="star2" class="ratings_stars{% if comment.score >= 2 %} ratings_over{% endif %}"></span>
						<span id="star3" class="ratings_stars{% if comment.score >= 3 %} ratings_over{% endif %}"></span>
						<span id="star4" class="ratings_stars{% if comment.score >= 4 %} ratings_over{% endif %}"></span>
						<span id="star5" class="ratings_stars{% if comment.score = 5 %} ratings_over{% endif %}"></span>
					</span> 
					<br /><br />
					{{ comment.comment}}
					</td>
				</tr>
				<tr><td id="reply_r" colspan="2"><a href="javascript: reply('{{comment.name}}')" style="float:right">reply</a></td></tr>
			{% endfor %}
		</table>
		<span style="float:left;padding:0 10px 0 5px;">Rate for {{ p.name }}</span>
		<span class='movie_choice'> 
			<span id="1" class="star_1 ratings_stars" onclick="loadXMLDoc('1')"></span>
			<span id="2" class="star_2 ratings_stars" onclick="loadXMLDoc('2')"></span>
			<span id="3" class="star_3 ratings_stars" onclick="loadXMLDoc('3')"></span>
			<span id="4" class="star_4 ratings_stars" onclick="loadXMLDoc('4')"></span>
			<span id="5" class="star_5 ratings_stars" onclick="loadXMLDoc('5')"></span>
		
		</span> 
		
			<input type="hidden" id="pid" value={{ p.id }} />
			<input type="hidden" id="average" value={{ average }} />
			
		<input type="hidden" id="myDiv" value="" />
		
		<table>
		<!--
			<th colspan="2">
				<label for="id_comment">Comment this product: </label>
			</th>
	-->		
			<tr>
				<td>
					<input type="hidden" id="product_id" value="{{ p.id }}" />
					<input type="hidden" id="time" value="{{ now }}" />
					Comments:
				</td>
				<td>
					<textarea name="comment" id="id_comment" rows="8" cols="60" ></textarea>
					<!--<input id="id_comment" type="textarea" /><br/>-->
				</td>
			</tr>
			<tr>
				<td>
					Name:
				</td>
				<td>
					<input id="name" type="text" /><br/>
				</td>
			</tr>
			<tr>
				<td>
					<input type="submit" value="Comment" id="add_comment" />
				</td>
			</tr>
		</table>
	</div>
</div>

<div class="highslide-html-content" id="highslide-html">
	<div class="highslide-header">
		<ul>
			<li class="highslide-move">
				<a href="#" onclick="return false">Move</a>
			</li>
			<li class="highslide-close">
				<a href="#" onclick="return hs.close(this)">Close</a>
			</li>
		</ul>
	</div>
	<div class="highslide-body">
	{{description}}
	</div>
</div>
{% endblock %}